apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-resource-demo
  labels:
    app: resource-demo
spec:
  replicas: 1  # The number of replicas for the deployment
  selector:
    matchLabels:
      app: resource-demo
  template:
    metadata:
      labels:
        app: resource-demo
    spec:
      containers:
      - name: app-container
        image: gcr.io/level-skyline-417610/demo:v1.1.0
        ports:
        - containerPort: 8080  # Exposing port 8080
        resources:
          requests:
            memory: "256Mi"  # Minimum memory request (256 Megabytes)
            cpu: "250m"  # Minimum CPU request (250 milli-cores)
          limits:
            memory: "512Mi"  # Maximum memory limit (512 Megabytes)
            cpu: "500m"  # Maximum CPU limit (500 milli-cores)